CC = g++
CCFLAGS = -std=c++11 -O2 -Wall 

base:base.cpp 
	${CC} ${CCFLAGS} $^ -o $@

unefective1:unefective1.cpp 
	${CC} ${CCFLAGS} $^ -o $@

unefective2:unefective2.cpp 
	${CC} ${CCFLAGS} $^ -o $@

efective1:efective1.cpp 
	${CC} ${CCFLAGS} $^ -o $@

efective2:efective2.cpp 
	${CC} ${CCFLAGS} $^ -o $@